checks:
    php:
        code_rating: true
        duplication: true
        variable_analysis: true
        unreachable_code: true
        unused_variables: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    php_analyzer: true
    php_code_coverage: true

build:
    environment:
        php:
            version: 8.1
            ini:
                xdebug.mode: coverage
    dependencies:
        before:
            - composer install --no-interaction
    tests:
        override:
            - php-scrutinizer-run
            - command: vendor/bin/phpunit --coverage-clover=coverage.xml
              coverage:
                  file: coverage.xml
                  format: clover
